### ISSUE TITLE
How to fix this error? 

### ISSUE THREAD

**Issue by dingjun6953** [cppalliance/boost-gecko#146]
When using MS visual studio 2019 Pro to build C++ executables the following error occurred and please see it: 
(Using Visual Studio 2019, VCPKG and CMake for building executables.) 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1189	#error:  Must not define both BOOST_FILESYSTEM_DYN_LINK and BOOST_FILESYSTEM_STATIC_LINK	C:\dev\TT2\TAS_Utils\out\build\x64-Release\TAS_Utils	C:\Users\john.zhang\vcpkg\installed\x64-windows\include\boost\filesystem\config.hpp	96	

How to fix above error? "Must not define both BOOST_FILESYSTEM_DYN_LINK and BOOST_FILESYSTEM_STATIC_LINK". 

I look forward to your reply! 

Thanks & Regards

![image](https://github.com/cppalliance/boost-gecko/assets/71055644/14ec9c50-c02e-4d79-b965-af12c19d544f)

**Comment by ashtum** [comment]
Sorry, this is a repository for the Boost Search widget. Could you please open an issue here: [https://github.com/boostorg/filesystem](https://github.com/boostorg/filesystem)?
