### ISSUE TITLE
"library_error" in QNX environment

### ISSUE THREAD

**Issue by xyy-jia** [cppalliance/boost-gecko#150]
`#include <iostream>
    #include <boost/interprocess/ipc/message_queue.hpp>
    #include <boost/interprocess/permissions.hpp>

    int main(){
    
        boost::interprocess::permissions permissions;
        printf("***************************** 1\n");

        int status = permissions.get_permissions();
        printf("***************************** 2 [0x%x]\n",status);

        // permissions.set_permissions(status); 
        // permissions.set_default();
        permissions.set_unrestricted();
        printf("***************************** 3.3\n");

        boost::interprocess::message_queue mq(boost::interprocess::open_or_create,"my_queue2",100,200);
        // mq.close();
        printf("***************************** 4\n");

        mq.remove("my_queue");
        printf("***************************** 5\n");

        return 0;
    }`

Always report an error in the QNX environment:
erminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  boost::interprocess_exception::library_error

**Comment by ashtum** [comment]
This is a repository for the Boost Search widget. Could you please open an issue here: https://github.com/boostorg/interprocess?

**Comment by xyy-jia** [comment]
OK

https://github.com/boostorg/interprocess/issues/241#issue-2710204315
